import type { ChecklistItem } from '@wholly/types';

export const CHECKLIST_ITEMS: Record<string, ChecklistItem[]> = {
  preparation: [
    {
      id: 'prep-1',
      stepId: 'preparation',
      title: '여권 유효기간 확인',
      description:
        '비자 신청 시 여권 유효기간이 최소 6개월 이상 남아있는지 확인',
      order: 1,
      isRequired: true,
    },
    {
      id: 'prep-2',
      stepId: 'preparation',
      title: '나이 자격 요건 확인',
      description: '만 18세~30세 이하인지 확인 (국가별 상이)',
      order: 2,
      isRequired: true,
    },
    {
      id: 'prep-3',
      stepId: 'preparation',
      title: '초기 정착 자금 준비',
      description: '최소 500만원 이상 준비 권장 (항공권, 숙박, 생활비)',
      order: 3,
      isRequired: true,
    },
    {
      id: 'prep-4',
      stepId: 'preparation',
      title: '워홀 국가 선택',
      description: '호주, 뉴질랜드, 캐나다 등 목적지 국가 결정',
      order: 4,
      isRequired: true,
    },
    {
      id: 'prep-5',
      stepId: 'preparation',
      title: '출발 시기 결정',
      description: '계절, 일자리 수요 등을 고려한 출발 시기 선택',
      order: 5,
      isRequired: false,
    },
    {
      id: 'prep-6',
      stepId: 'preparation',
      title: '영어 실력 점검',
      description: '기본적인 의사소통 가능한 수준 확인',
      order: 6,
      isRequired: false,
    },
    {
      id: 'prep-7',
      stepId: 'preparation',
      title: '워홀 정보 수집',
      description: '커뮤니티, 블로그, 유튜브 등에서 경험담 확인',
      order: 7,
      isRequired: false,
    },
    {
      id: 'prep-8',
      stepId: 'preparation',
      title: '가족 동의 구하기',
      description: '가족과 충분히 상의하고 동의 얻기',
      order: 8,
      isRequired: false,
    },
  ],
  'visa-application': [
    {
      id: 'visa-1',
      stepId: 'visa-application',
      title: 'ImmiAccount 계정 생성',
      description: '호주 이민성 웹사이트에서 계정 생성',
      order: 1,
      isRequired: true,
    },
    {
      id: 'visa-2',
      stepId: 'visa-application',
      title: '여권 사본 준비',
      description: '여권 정보면 스캔 또는 사진 촬영',
      order: 2,
      isRequired: true,
    },
    {
      id: 'visa-3',
      stepId: 'visa-application',
      title: '증명사진 준비',
      description: '여권용 사진 규격에 맞는 사진 준비',
      order: 3,
      isRequired: true,
    },
    {
      id: 'visa-4',
      stepId: 'visa-application',
      title: '은행 잔고 증명서 발급',
      description: '최소 500만원 이상 잔고 증명 (영문)',
      order: 4,
      isRequired: true,
    },
    {
      id: 'visa-5',
      stepId: 'visa-application',
      title: '비자 신청서 작성',
      description: 'Working Holiday visa (subclass 417) 온라인 신청',
      order: 5,
      isRequired: true,
    },
    {
      id: 'visa-6',
      stepId: 'visa-application',
      title: '비자 수수료 결제',
      description: '약 $635 AUD 신용카드로 결제',
      order: 6,
      isRequired: true,
    },
    {
      id: 'visa-7',
      stepId: 'visa-application',
      title: '건강검진 예약',
      description: '지정 병원에서 건강검진 받기 (필요시)',
      order: 7,
      isRequired: false,
    },
    {
      id: 'visa-8',
      stepId: 'visa-application',
      title: '비자 승인 대기',
      description: '평균 2주~4주 소요, 이메일 확인',
      order: 8,
      isRequired: true,
    },
    {
      id: 'visa-9',
      stepId: 'visa-application',
      title: '비자 승인 레터 저장',
      description: '승인 이메일 및 PDF 파일 저장',
      order: 9,
      isRequired: true,
    },
  ],
  'pre-departure': [
    {
      id: 'dep-1',
      stepId: 'pre-departure',
      title: '항공권 예약',
      description: '편도 또는 왕복 항공권 예약 (3개월 전 예약 권장)',
      order: 1,
      isRequired: true,
    },
    {
      id: 'dep-2',
      stepId: 'pre-departure',
      title: '여행자 보험 가입',
      description: '해외 체류 기간 동안의 보험 가입 (최소 3개월)',
      order: 2,
      isRequired: true,
    },
    {
      id: 'dep-3',
      stepId: 'pre-departure',
      title: '국제 운전면허증 발급',
      description: '현지에서 운전 계획이 있다면 발급',
      order: 3,
      isRequired: false,
    },
    {
      id: 'dep-4',
      stepId: 'pre-departure',
      title: '신용/체크카드 준비',
      description: '해외 결제 가능한 카드 2개 이상 준비',
      order: 4,
      isRequired: true,
    },
    {
      id: 'dep-5',
      stepId: 'pre-departure',
      title: '환전하기',
      description: '초기 생활비 $500~1000 AUD 환전',
      order: 5,
      isRequired: true,
    },
    {
      id: 'dep-6',
      stepId: 'pre-departure',
      title: '짐싸기 체크리스트 작성',
      description: 'AI 추천 짐싸기 리스트 활용',
      order: 6,
      isRequired: true,
    },
    {
      id: 'dep-7',
      stepId: 'pre-departure',
      title: '영문 이력서 준비',
      description: '구직을 위한 영문 이력서 작성',
      order: 7,
      isRequired: false,
    },
    {
      id: 'dep-8',
      stepId: 'pre-departure',
      title: '예방접종 확인',
      description: '필요한 예방접종 확인 및 접종',
      order: 8,
      isRequired: false,
    },
    {
      id: 'dep-9',
      stepId: 'pre-departure',
      title: '중요 서류 사본 준비',
      description: '여권, 비자, 보험 등 사본 및 디지털 백업',
      order: 9,
      isRequired: true,
    },
  ],
  accommodation: [
    {
      id: 'acc-1',
      stepId: 'accommodation',
      title: '숙소 유형 결정',
      description: '백패커, 한인민박, 에어비앤비 중 선택',
      order: 1,
      isRequired: true,
    },
    {
      id: 'acc-2',
      stepId: 'accommodation',
      title: '위치 선정',
      description: 'CBD, 교외 등 위치 결정',
      order: 2,
      isRequired: true,
    },
    {
      id: 'acc-3',
      stepId: 'accommodation',
      title: '예약 플랫폼 선택',
      description: 'Booking.com, Hostelworld, Airbnb 등',
      order: 3,
      isRequired: true,
    },
    {
      id: 'acc-4',
      stepId: 'accommodation',
      title: '리뷰 확인',
      description: '최소 10개 이상 리뷰 읽기, 빈대 주의',
      order: 4,
      isRequired: true,
    },
    {
      id: 'acc-5',
      stepId: 'accommodation',
      title: '1-2주 숙박 예약',
      description: '초기 정착 기간 동안 머물 숙소 예약',
      order: 5,
      isRequired: true,
    },
    {
      id: 'acc-6',
      stepId: 'accommodation',
      title: '예약 확정서 저장',
      description: '예약 확인 이메일 및 바우처 저장',
      order: 6,
      isRequired: true,
    },
    {
      id: 'acc-7',
      stepId: 'accommodation',
      title: '체크인 시간 확인',
      description: '도착 시간과 체크인 시간 조율',
      order: 7,
      isRequired: true,
    },
    {
      id: 'acc-8',
      stepId: 'accommodation',
      title: '숙소 위치 파악',
      description: '공항에서 숙소까지 이동 경로 확인',
      order: 8,
      isRequired: false,
    },
  ],
  arrival: [
    {
      id: 'arr-1',
      stepId: 'arrival',
      title: '입국 카드 작성',
      description: '비행기 내에서 입국 카드 작성',
      order: 1,
      isRequired: true,
    },
    {
      id: 'arr-2',
      stepId: 'arrival',
      title: '입국 심사 통과',
      description: '비자 승인 레터 및 여권 제시',
      order: 2,
      isRequired: true,
    },
    {
      id: 'arr-3',
      stepId: 'arrival',
      title: '짐 찾기 및 세관 통과',
      description: '수하물 찾고 세관 신고',
      order: 3,
      isRequired: true,
    },
    {
      id: 'arr-4',
      stepId: 'arrival',
      title: '현지 SIM 카드 구매',
      description: 'Optus, Telstra, Vodafone 등에서 구매',
      order: 4,
      isRequired: true,
    },
    {
      id: 'arr-5',
      stepId: 'arrival',
      title: '교통카드 발급',
      description: 'Opal 카드(시드니) 또는 Myki(멜버른) 구매',
      order: 5,
      isRequired: true,
    },
    {
      id: 'arr-6',
      stepId: 'arrival',
      title: '숙소로 이동',
      description: '공항에서 숙소까지 대중교통 또는 택시 이용',
      order: 6,
      isRequired: true,
    },
    {
      id: 'arr-7',
      stepId: 'arrival',
      title: '숙소 체크인',
      description: '예약 확인서 제시 및 체크인',
      order: 7,
      isRequired: true,
    },
    {
      id: 'arr-8',
      stepId: 'arrival',
      title: '주변 환경 파악',
      description: '슈퍼마켓, 약국 등 주변 시설 확인',
      order: 8,
      isRequired: false,
    },
  ],
  'bank-account': [
    {
      id: 'bank-1',
      stepId: 'bank-account',
      title: '은행 선택',
      description: 'Commonwealth, NAB, ANZ, Westpac 중 선택',
      order: 1,
      isRequired: true,
    },
    {
      id: 'bank-2',
      stepId: 'bank-account',
      title: '필요 서류 준비',
      description: '여권, 비자, 주소 증명서류 준비',
      order: 2,
      isRequired: true,
    },
    {
      id: 'bank-3',
      stepId: 'bank-account',
      title: '은행 방문 예약',
      description: '온라인 또는 전화로 방문 예약',
      order: 3,
      isRequired: false,
    },
    {
      id: 'bank-4',
      stepId: 'bank-account',
      title: '계좌 개설',
      description: '은행 지점 방문하여 계좌 개설',
      order: 4,
      isRequired: true,
    },
    {
      id: 'bank-5',
      stepId: 'bank-account',
      title: '체크카드 발급',
      description: '직불카드 발급 신청 (우편 수령)',
      order: 5,
      isRequired: true,
    },
    {
      id: 'bank-6',
      stepId: 'bank-account',
      title: '온라인 뱅킹 설정',
      description: '모바일 앱 다운로드 및 계정 설정',
      order: 6,
      isRequired: true,
    },
    {
      id: 'bank-7',
      stepId: 'bank-account',
      title: 'BSB 및 계좌번호 확인',
      description: '급여 입금을 위한 계좌 정보 확인',
      order: 7,
      isRequired: true,
    },
    {
      id: 'bank-8',
      stepId: 'bank-account',
      title: '한국에서 송금 테스트',
      description: '소액 송금하여 계좌 정상 작동 확인',
      order: 8,
      isRequired: false,
    },
  ],
  tfn: [
    {
      id: 'tfn-1',
      stepId: 'tfn',
      title: 'TFN 신청 자격 확인',
      description: '워킹홀리데이 비자 소지자 확인',
      order: 1,
      isRequired: true,
    },
    {
      id: 'tfn-2',
      stepId: 'tfn',
      title: 'ATO 웹사이트 접속',
      description: 'Australian Taxation Office 웹사이트 방문',
      order: 2,
      isRequired: true,
    },
    {
      id: 'tfn-3',
      stepId: 'tfn',
      title: '온라인 신청서 작성',
      description: '개인정보 및 비자 정보 입력',
      order: 3,
      isRequired: true,
    },
    {
      id: 'tfn-4',
      stepId: 'tfn',
      title: '호주 주소 입력',
      description: '현재 거주 중인 주소 입력 (숙소 주소)',
      order: 4,
      isRequired: true,
    },
    {
      id: 'tfn-5',
      stepId: 'tfn',
      title: '신청 완료 확인',
      description: '신청 확인 이메일 수신',
      order: 5,
      isRequired: true,
    },
    {
      id: 'tfn-6',
      stepId: 'tfn',
      title: 'TFN 승인 대기',
      description: '28일 이내 우편 또는 이메일로 수령',
      order: 6,
      isRequired: true,
    },
    {
      id: 'tfn-7',
      stepId: 'tfn',
      title: 'TFN 번호 안전하게 보관',
      description: '분실 시 재발급 어려움, 안전하게 보관',
      order: 7,
      isRequired: true,
    },
    {
      id: 'tfn-8',
      stepId: 'tfn',
      title: '고용주에게 TFN 제출',
      description: '일자리 구한 후 고용주에게 TFN 제공',
      order: 8,
      isRequired: false,
    },
  ],
  settlement: [
    {
      id: 'set-1',
      stepId: 'settlement',
      title: '쉐어하우스 검색',
      description: 'Flatmates.com.au, Gumtree 등에서 검색',
      order: 1,
      isRequired: true,
    },
    {
      id: 'set-2',
      stepId: 'settlement',
      title: '인스펙션 예약',
      description: '최소 3-5곳 직접 방문하여 확인',
      order: 2,
      isRequired: true,
    },
    {
      id: 'set-3',
      stepId: 'settlement',
      title: '계약 조건 확인',
      description: '렌트비, 본드, 최소 거주 기간 확인',
      order: 3,
      isRequired: true,
    },
    {
      id: 'set-4',
      stepId: 'settlement',
      title: '본드 지불',
      description: '보증금 지불 (보통 2-4주 렌트비)',
      order: 4,
      isRequired: true,
    },
    {
      id: 'set-5',
      stepId: 'settlement',
      title: '계약서 작성',
      description: '계약서 꼼꼼히 읽고 서명',
      order: 5,
      isRequired: true,
    },
    {
      id: 'set-6',
      stepId: 'settlement',
      title: '이사 및 입주',
      description: '짐 옮기고 방 정리',
      order: 6,
      isRequired: true,
    },
    {
      id: 'set-7',
      stepId: 'settlement',
      title: '영문 이력서 업데이트',
      description: '호주 형식에 맞게 이력서 수정',
      order: 7,
      isRequired: true,
    },
    {
      id: 'set-8',
      stepId: 'settlement',
      title: '구직 플랫폼 등록',
      description: 'Seek, Indeed, Gumtree에 이력서 등록',
      order: 8,
      isRequired: true,
    },
    {
      id: 'set-9',
      stepId: 'settlement',
      title: '일자리 지원',
      description: '레스토랑, 카페, 농장 등 지원',
      order: 9,
      isRequired: true,
    },
    {
      id: 'set-10',
      stepId: 'settlement',
      title: '면접 준비',
      description: '자기소개 및 간단한 영어 면접 연습',
      order: 10,
      isRequired: false,
    },
  ],
};

export function getChecklistByStepId(stepId: string): ChecklistItem[] {
  return CHECKLIST_ITEMS[stepId] ?? [];
}

export function getChecklistItemById(
  itemId: string,
): ChecklistItem | undefined {
  for (const items of Object.values(CHECKLIST_ITEMS)) {
    const found = items.find((item) => item.id === itemId);
    if (found) return found;
  }
  return undefined;
}

export function getRequiredItems(stepId: string): ChecklistItem[] {
  return getChecklistByStepId(stepId).filter((item) => item.isRequired);
}

export function getOptionalItems(stepId: string): ChecklistItem[] {
  return getChecklistByStepId(stepId).filter((item) => !item.isRequired);
}
